### ISSUE TITLE
Docker image runs with CLI argument for bolt path

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1739]
Hi!

While this is  to be expected, the CLI argument "-b" overrides the environment variable "BOLT_PATH", causes head aches when using docker to run chronograf.

Does it have to be running with -b as default?

My docker-compose file (the related parts):
```
    chronograf:
        image: quay.io/influxdb/chronograf
        volumes: 
            - ./data:/data/
        environment:
            - BOLT_PATH=/data/chronograf/chronograf-v1.db
```
looking inside the container:
```
/ # ps
PID   USER     TIME   COMMAND
    1 root       0:00 /usr/bin/chronograf -b /var/lib/chronograf/chronograf-v1.db -c /usr/share/chronograf/canned
```

This causes my bolt db to be written inside the container and not saved outside.

Solution:
```
    chronograf:
        image: quay.io/influxdb/chronograf
        command: chronograf
        volumes: 
            - ./data:/data/
        environment:
            - BOLT_PATH=/data/chronograf/chronograf-v1.db
```

This will then use the environment variables as configuration instead of the command line argument.
