### ISSUE TITLE
Add jwt security to all /chronograf/v1/routes

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#228]
... well, all but /auth

In swagger:

``` yaml
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
```

For all routes but /auth require bearer:

``` yaml
      security:
            - bearer: []
```

Add security checking similar to [goswagger-jwt](https://github.com/manell/goswagger-jwt)

Check `exp`, `iss`, `nbf`.

Make sure to check `alg` as well.
