### ISSUE TITLE
Canned mongo App not showing up in chronograf

### ISSUE THREAD

**Issue by Puneeth-n** [influxdata/chronograf#4266]
**docker image**: chronograf:1.6

**docker-compose.yml**
```
version: '2'
services:
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: influxdb:1.6
    container_name: influxdb
    volumes:
      # Mount for influxdb data directory
      - influx-data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089"

  kapacitor:
    # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
    image: kapacitor:1.5
    container_name: kapacitor
    volumes:
      # Mount for kapacitor data directory
      - kapacitor-data:/var/lib/kapacitor
      # Mount for kapacitor configuration
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf
    # Kapacitor requires network access to Influxdb
    links:
      - influxdb
    ports:
      # The API for Kapacitor is served on port 9092
      - "9092:9092"

  chronograf:
    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
    image: chronograf:1.6
    container_name: chronograf
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_USERNAME: ""
      INFLUXDB_PASSWORD: ""
      KAPACITOR_URL: "http://kapacitor:9092"
      KAPACITOR_USERNAME: ""
      KAPACITOR_PASSWORD: ""
      LOG_LEVEL: "debug"
    volumes:
      # Mount for chronograf database
      - chronograf-data:/var/lib/chronograf
    links:
      # Chronograf requires network access to InfluxDB and Kapacitor
      - influxdb
      - kapacitor
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb

volumes:
  influx-data:
  chronograf-data:
  kapacitor-data:

```

**Some debug logs**
```
time="2018-08-22T13:47:08Z" level=debug msg=query command="SELECT mean(\"usage_user\") FROM \"telegraf\".\"\".\"cpu\" WHERE \"cpu\" = 'cpu-total' AND time > now() - 10m GROUP BY host;\n      SELECT mean(\"load1\") FROM \"telegraf\".\"\".\"system\" WHERE time > now() - 10m GROUP BY host;\n      SELECT non_negative_derivative(mean(uptime)) AS deltaUptime FROM \"telegraf\".\"\".\"system\" WHERE time > now() - 1m0s * 10 GROUP BY host, time(1m0s) fill(0);\n      SELECT mean(\"Percent_Processor_Time\") FROM \"telegraf\".\"\".\"win_cpu\" WHERE time > now() - 10m GROUP BY host;\n      SELECT mean(\"Processor_Queue_Length\") FROM \"telegraf\".\"\".\"win_system\" WHERE time > now() - 10s GROUP BY host;\n      SELECT non_negative_derivative(mean(\"System_Up_Time\")) AS winDeltaUptime FROM \"telegraf\".\"\".\"win_system\" WHERE time > now() - 1m0s * 10 GROUP BY host, time(1m0s) fill(0);\n      SHOW TAG VALUES WITH KEY = \"host\";" component=proxy db=telegraf host="influxdb:8086" rp=
time="2018-08-22T13:47:08Z" level=info msg="Response: OK" component=server method=POST remote_addr="10.6.1.209:61012" response_time=15.44558ms status=200
time="2018-08-22T13:47:08Z" level=debug msg=Request component=server method=POST remote_addr="10.6.1.209:61012" url=/chronograf/v1/sources/0/proxy
time="2018-08-22T13:47:08Z" level=debug msg=query command="show series from /^diskio$|^docker$|^elasticsearch_indices$|^influxdb_write$|^kubernetes_pod_container$|^net$|^apache$|^disk$|^rabbitmq_node$|^ping$|^processes$|^kubernetes_pod_network$|^procstat$|^win_net$|^consul_consul_http_GET_v1_health_state__$|^nsq_topic$|^influxdb_queryExecutor$|^kubernetes_system_container$|^system$|^memcached$|^nsq_server$|^docker_container_blkio$|^influxdb_httpd$|^phpfpm$|^win_websvc$|^haproxy$|^netstat$|^kubernetes_node$|^mem$|^mysql$|^riak$|^win_mem$|^consul_memberlist_msg_alive$|^consul_serf_events$|^postgresql$|^redis$|^mesos$|^nginx$|^consul_raft_state_candidate$|^cpu$|^docker_container_net$|^influxdb_database$|^nsq_channel$|^win_cpu$|^consul_health_checks$|^consul_consul_fsm_register$|^win_system$/" component=proxy db=telegraf host="influxdb:8086" rp=
time="2018-08-22T13:47:08Z" level=info msg="Response: OK" component=server method=POST remote_addr="10.6.1.209:61012" response_time=138.71869ms status=200
time="2018-08-22T13:47:10Z" level=debug msg=Request component=server method=GET remote_addr="10.6.1.209:61012" url=/chronograf/v1/me
time="2018-08-22T13:47:10Z" level=info msg="Response: OK" component=server method=GET remote_addr="10.6.1.209:61012" response_time="66.068µs" status=200
time="2018-08-22T13:47:22Z" level=debug msg=Request component=server method=GET remote_addr="10.6.1.209:61012" url=/chronograf/v1/me
time="2018-08-22T13:47:22Z" level=info msg="Response: OK" component=server method=GET remote_addr="10.6.1.209:61012" response_time="63.954µs" status=200
```

**telegraf.conf**
```
[global_tags]
  region = "eu-west-1"
  az = "eu-west-1a"
  env = "delta"

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = "db-exporter"
  omit_hostname = false

[[inputs.system]]

[[inputs.cpu]]
  percpu = true
  totalcpu = true

[[inputs.influxdb]]
  urls = ["http://influxdb.delta-net0ps.com:8086/debug/vars"]

[[inputs.mongodb]]
  servers = ["mongodb://mongo-0.delta-net0ps.com:27037"]

[[outputs.influxdb]]
  urls = ["http://influxdb.delta-net0ps.com:8086"]
  database = "telegraf"
  username = ""
  password = ""
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
```
