### ISSUE TITLE
 Chronograf (1.7.10) Expected number or array but got string: success.

### ISSUE THREAD

**Issue by xMTinkerer** [influxdata/chronograf#5207]
*What browser are you using (name and version)?*
Chrome 74.0.3729.169 (Official Build) (64-bit)
*What operating system are you using?*
macOS Mojave 10.14.5

*Please describe what you were trying to do when you encountered this error:*
I was trying to configure an Alert Rule for a Threshold value for this http_response:

```toml
 # HTTP/HTTPS request given an address a method and a timeout
 [[inputs.http_response]]
   name_suffix = "_openhabianpi"
   ## Server address (default http://localhost)
   address = "http://openhabianpi:8080"
   ## Set response_timeout (default 5 seconds)
   response_timeout = "5s"
   ## HTTP Request Method
   method = "GET"
   ## Whether to follow redirects from the server (defaults to false)
   follow_redirects = true
```

This is my Alert Rule:
![image](https://user-images.githubusercontent.com/10202041/59527976-e7b03e00-8e91-11e9-9092-247f0a22a8bf.png)
Clicking the `here` link brought me to this github issue and here is the error... apparently:
```
Error: Expected number or array but got string: success.
    at j (http://192.168.2.35:8888/src.6c53cef1.js:3158:1898)
    at W.parseArray_ (http://192.168.2.35:8888/src.6c53cef1.js:3158:31911)
    at W.start_ (http://192.168.2.35:8888/src.6c53cef1.js:3158:35574)
    at W.updateOptions (http://192.168.2.35:8888/src.6c53cef1.js:3158:36541)
    at d.value (http://192.168.2.35:8888/src.6c53cef1.js:3218:4878)
    at xi (http://192.168.2.35:8888/src.6c53cef1.js:716:84251)
    at wi (http://192.168.2.35:8888/src.6c53cef1.js:716:79945)
    at ki (http://192.168.2.35:8888/src.6c53cef1.js:716:79561)
    at Ha (http://192.168.2.35:8888/src.6c53cef1.js:716:78073)
    at Object.enqueueSetState (http://192.168.2.35:8888/src.6c53cef1.js:716:47062)
```

I can see values when I explore the data:

And here is the "Explore" showing the `success` value:
![image](https://user-images.githubusercontent.com/10202041/59527991-f5fe5a00-8e91-11e9-9691-e8dbb851bc41.png)
