### ISSUE TITLE
How to use/enable predefined canned dashboard templates?

### ISSUE THREAD

**Issue by zshamrock** [influxdata/chronograf#693]
In the `README.md` it says:
_Chronograf's pre-canned dashboards for the supported Telegraf input plugins. Currently, Chronograf offers dashboard templates for the following Telegraf input plugins:_

But when I run the Chronograf (I run from Docker if it matters), I only see Kubernetes Dashboard.

How I can enable and use other available pre-canned dashboards in Chronograf?

**Comment by rlex** [comment]
if you have host reporting to influxdb from telegraf, those dashboards should be available on host listing.

**Comment by 121watts** [comment]
@zshamrock, @rlex is correct.  Click on Host List and each host should have predefined apps (dashboards).

**Comment by jackzampolin** [comment]
@zshamrock If you aren't running the `system` and `cpu` plugins then they won't show up on the hostlist. This isn't well documented. If you run into issues you can post here

**Comment by goller** [comment]
@zshamrock Thanks for writing in... btw, @jackzampolin has created kubernetes daemon sets and telegraf configurations:

https://github.com/jackzampolin/tick-kube/blob/master/telegraf

Check out his telegraf configuration.  In a docker environment you could use everything in it except dns, kubernetes and prometheus/etcd monitoring.

Also, check out his daemonset.yaml... the big thing is mounting /proc, /sys and such into the docker container running telegraf _AND_ set the `HOST_PROC` and `HOST_SYS` environment variables.

**Comment by zshamrock** [comment]
Hi, guys, there is a medium post published today https://medium.com/picnic-engineering/tick-tock-5f0cc49ac5e1, you might be interested to take a look. 

There you can see that I've enabled RabbitMQ and MongoDB plugins, but still in the Host List saw only Kubernetes dashboards.

**Comment by goller** [comment]
Hey @zshamrock thanks for the post!  It's great to see you using it!
So, I think you'll be able to get the rabbitmq and mongo dashboards working with just one change to your configuration.

Add cpu and system to telegraf configuration like this:

```
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false

[[inputs.system]]
```

Now, that should be all you need to do. 

However, if you want to collect information about the host that the telegraf docker container is running on then you would modify your docker compose like this:

```

services:
  telegraf:
    image: telegraf:1.1.2
    container_name: telegraf1.1.2
    # use network_mode: "service:influxdb" to be able to use http://localhost:8086 to connect influxdb output plugin
    # an alternative option would be to specify 
    # networks: 
    #   - influxdb
    # which puts both Telegraf and InfluxDB on the same network, 
    # but does require to update conf/telegraf.conf: set urls of [[output.influxdb]] into http://influxdb:8086          
    network_mode: "service:influxdb"
    volumes:
      - $PWD/conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/rootfs/proc
      - /sys:/rootfs/sys
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
    depends_on:
      - influxdb
```

Note: this docker compose would only work on linux.

So, if you have time would you let us know if you like the pre-canned metrics we created for rabbitmq and mongodb?
